d1 create a chess board
annam23/PY-111 pull request #11
Opened 2022-02-26 09:53 UTC by annam23

Начала задачу с построения и вывода двумерного массива в виде доски. Но немного их подзабыла, в итоге первый элемент, откуда будем двигаться, верхний левый, а не нижний угол. Что нужно исправить?

2022-03-12 08:09 UTC, EnotYoyo commented
Верний левый или нижний левый - это только отображение. 
Но если хочется сделать правильно отображение, то строки нужно выводить в обратном порядке (не от 0 к N, а от N к 0)

2022-03-12 08:21 UTC, annam23 commented
да, я поняла, что дело в отображении только. а по остальному коду есть замечания? или pull request можно закрывать?

2022-03-12 08:30 UTC, EnotYoyo requested changes
2 теста падают на этом коде

2022-03-12 08:30 UTC, EnotYoyo commented on Tasks/d1_horse.py
> +                    board[row + 1][elem + 2] += CONST_WAY * board[row][elem]
Вот эта строка дублируется по сути. Подумайте, как можно записать через цикл это дело :)

2022-03-14 07:35 UTC, EnotYoyo approved these changes
Принято :)

2022-03-14 07:35 UTC, EnotYoyo commented on Tasks/d1_horse.py
> +            board[row][elem] += CONST_WAY * (board[row - 1][elem + 2] + board[row - 1][elem - 2] + board[row - 2][elem + 1] + board[row - 2][elem - 1])
хех :) 
Увеличить доску, чтобы не выходить за пределы доски...) 

Я вообще думал про какое-то такое решение: 
```python
possible_turns = [(1, 2), (2, 1), (1, -2), (2, -1)]
for dif_x, dif_y in possible_turns:
    .... # проверка на выход за границы массива и совершение "хода"
```

2022-03-14 09:20 UTC, merged