b1 ex done, sin x - с вопросом
annam23/PY-111 pull request #14
Opened 2022-03-10 18:46 UTC by annam23

2022-03-12 08:16 UTC, EnotYoyo requested changes

2022-03-12 08:16 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        res += (x ** elem) / factorial
А числитель тоже можно считать с помощью предыдущего значения :)

2022-03-12 08:16 UTC, EnotYoyo commented on Tasks/b2_Taylor.py
> +        res += ((-1) ** elem) * (x ** (2 * elem + 1)) / fact
Здесь аналогично :)

2022-03-15 18:30 UTC, annam23 commented
Поменяла числители, теперь расчет по предыдущему. 
Затык в sin x остался, не понимаю, в каком моенте и почему не проходит тест по нему

2022-03-16 14:23 UTC, EnotYoyo commented
> Поменяла числители, теперь расчет по предыдущему. Затык в sin x остался, не понимаю, в каком моенте и почему не проходит тест по нему

Попробуйте расписать несколько первых элементов и распечатать их в программе. 
У Вас неправильная формула.

2022-03-16 15:37 UTC, annam23 commented
> 

Спасибо, увидела!

2022-03-17 06:16 UTC, EnotYoyo approved these changes
Принято!

2022-03-17 06:23 UTC, merged