g2 done
annam23/PY-111 pull request #17
Opened 2022-03-13 14:10 UTC by annam23

g2 простейшая реализация

2022-03-14 07:37 UTC, EnotYoyo requested changes

2022-03-14 07:37 UTC, EnotYoyo commented on Tasks/g2_quick_sort.py
> +    left = [value for value in container if value < pivot]
Конкретно в такой реализации плохо то, что по контейнеру проходим 3 раза, хотя одного достаточно. 
Поэтому тут лучше использовать простой цикл.

2022-03-15 18:38 UTC, annam23 commented on Tasks/g2_quick_sort.py
> +    left = [value for value in container if value < pivot]
Поняла, исправила!

2022-03-16 14:26 UTC, EnotYoyo approved these changes
Принято!

2022-03-16 14:51 UTC, merged